import Link from "next/link";
import { ArrowRight, Bot, Check, FileSearch, Film, ReceiptText, ShieldCheck, Sparkles } from "lucide-react";

const steps = [
  { n:"01", title:"Research", body:"Start with the customer pain and the mechanism that actually solves it.", icon:FileSearch },
  { n:"02", title:"Gate", body:"Inspect the scripts and production plan before any paid generation call.", icon:ShieldCheck },
  { n:"03", title:"Generate", body:"Approve the spend, then route the exact plan through the configured media provider.", icon:Film },
  { n:"04", title:"Prove", body:"Keep the request, state, QA trail, and publish approval attached to the work.", icon:ReceiptText },
];

export default function LandingPage() {
  return <main className="min-h-screen bg-[#f4f3ef] text-[#151613]">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8">
      <Link href="/" className="text-lg font-semibold tracking-[-0.04em]">Social Studio</Link>
      <nav className="hidden items-center gap-7 text-sm text-black/52 md:flex"><Link href="#factory">Factory</Link><Link href="#proof">Proof</Link><Link href="#agents">Agents</Link><Link href="/pricing">Pilot</Link></nav>
      <div className="flex items-center gap-2"><Link href="/studio" className="hidden rounded-full px-4 py-2 text-sm font-medium sm:block">Open studio</Link><Link href="/studio/create" className="rounded-full bg-black px-4 py-2.5 text-sm font-medium text-white">Build a batch</Link></div>
    </header>

    <section className="mx-auto max-w-7xl px-5 pb-16 pt-16 text-center sm:px-8 sm:pt-24">
      <div className="mx-auto inline-flex items-center gap-2 rounded-full border border-black/8 bg-white px-3.5 py-2 text-[10px] font-semibold uppercase tracking-[0.15em] text-black/48"><Sparkles className="h-3.5 w-3.5 text-[#2357ff]"/>UGC ad factory for DTC teams</div>
      <h1 className="mx-auto mt-6 max-w-6xl text-balance text-5xl font-semibold leading-[.92] tracking-[-0.075em] sm:text-7xl lg:text-[94px]">Find the angle.<br/>Make the ad.<br/><span className="text-black/35">Prove what works.</span></h1>
      <p className="mx-auto mt-7 max-w-2xl text-balance text-base leading-7 text-black/52 sm:text-lg">Turn product truth into testable UGC without starting from a blank prompt. Research the pain. Gate the script. Approve the render. Keep the receipt.</p>
      <div className="mt-8 flex flex-col justify-center gap-2 sm:flex-row"><Link href="/studio/create" className="inline-flex items-center justify-center gap-2 rounded-full bg-black px-6 py-3 text-sm font-medium text-white">Build your first batch <ArrowRight className="h-4 w-4"/></Link><Link href="/pricing" className="inline-flex items-center justify-center rounded-full border border-black/10 bg-white px-6 py-3 text-sm font-medium">See the $249 pilot</Link></div>
      <div className="mx-auto mt-8 flex max-w-2xl flex-wrap justify-center gap-x-5 gap-y-2 text-[11px] text-black/40"><span className="inline-flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-[#159653]"/>No model lock-in</span><span className="inline-flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-[#159653]"/>Paid renders require approval</span><span className="inline-flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-[#159653]"/>Scripts + receipts stay inspectable</span></div>

      <div className="relative mx-auto mt-16 max-w-6xl overflow-hidden rounded-[30px] border border-black/8 bg-[#deded9] p-3 text-left shadow-[0_35px_110px_rgba(0,0,0,.14)]">
        <div className="rounded-[24px] bg-[#fbfbf9] p-5 sm:p-7">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs text-black/38">Batch · Product launch</p><h2 className="mt-1 text-xl font-semibold tracking-tight">Three angles. One production contract.</h2></div><span className="self-start rounded-full bg-[#ecf8f1] px-3 py-1.5 text-[10px] font-semibold text-[#117341]">GATE PASSED</span></div>
          <div className="mt-6 grid gap-3 md:grid-cols-4">{steps.map(({n,title,body,icon:Icon},index)=><article key={title} className={`rounded-2xl border p-4 ${index===2?"border-[#2357ff]/15 bg-[#edf1ff]":"border-black/7 bg-white"}`}><div className="flex items-center justify-between"><span className="text-[9px] font-semibold tracking-[.14em] text-black/28">{n}</span><Icon className="h-4 w-4 text-black/35"/></div><p className="mt-5 text-sm font-semibold">{title}</p><p className="mt-2 text-[11px] leading-5 text-black/43">{body}</p></article>)}</div>
          <div className="mt-3 grid gap-3 md:grid-cols-[1.3fr_.7fr]">
            <div className="rounded-2xl bg-[#10110f] p-5 text-white"><div className="flex items-center gap-2 text-xs text-white/42"><Film className="h-4 w-4 text-[#b9ff66]"/>Clip 1 · problem and tension</div><p className="mt-4 max-w-xl text-lg leading-7 tracking-[-0.02em]">“I kept paying for coffee that still tasted flat. Better beans did not fix the part I was getting wrong every morning.”</p><div className="mt-5 flex flex-wrap gap-2 text-[9px]"><span className="rounded-full bg-white/10 px-3 py-1.5">24 WORDS</span><span className="rounded-full bg-white/10 px-3 py-1.5">NO SALES CLOSER</span><span className="rounded-full bg-[#b9ff66] px-3 py-1.5 text-black">READY FOR APPROVAL</span></div></div>
            <div className="rounded-2xl border border-black/7 bg-white p-5"><div className="flex items-center gap-2"><ReceiptText className="h-4 w-4 text-[#2357ff]"/><p className="text-xs font-medium">Proof state</p></div><div className="mt-4 space-y-3"><ProofRow text="Research brief recorded" done/><ProofRow text="Script gate passed" done/><ProofRow text="Paid render approved"/><ProofRow text="Provider receipt"/></div></div>
          </div>
        </div>
      </div>
    </section>

    <section className="border-y border-black/7 bg-[#e8e7e3] py-8"><div className="mx-auto flex max-w-5xl flex-wrap items-center justify-center gap-x-10 gap-y-4 px-5 text-[10px] font-semibold tracking-[0.14em] text-black/34"><span>SHOPIFY</span><span>DTC BRANDS</span><span>CREATIVE TEAMS</span><span>AGENCIES</span><span>AGENTS</span></div></section>

    <section id="factory" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28">
      <div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div className="lg:sticky lg:top-12"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-black/35">The factory</p><h2 className="mt-4 max-w-xl text-4xl font-semibold leading-[1.01] tracking-[-0.06em] sm:text-5xl">Do the thinking before the rendering.</h2><p className="mt-5 max-w-lg text-base leading-7 text-black/50">Most video tools make generation easy. Social Studio makes the decision trail visible before generation starts, so a team or agent can tell what it is testing and why.</p></div><div className="grid gap-3 sm:grid-cols-2">{steps.map(({title,body,icon:Icon},index)=><article key={title} className="rounded-[24px] border border-black/7 bg-white p-6 sm:p-7"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#f0f0ed]"><Icon className="h-4 w-4"/></div><p className="mt-6 text-[10px] uppercase tracking-[.15em] text-black/32">Step {index+1}</p><h3 className="mt-2 text-xl font-semibold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-6 text-black/46">{body}</p></article>)}</div></div>
    </section>

    <section id="proof" className="bg-[#10110f] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-28">
      <div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-white/35">Trust by design</p><h2 className="mt-4 max-w-2xl text-4xl font-semibold leading-[1.01] tracking-[-0.06em] sm:text-5xl">A render is not proof. A receipt is not performance.</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/48">The studio keeps states separate: planned, gate passed, approved to spend, render queued, reviewed, published. Performance only enters the record when real campaign data exists.</p><div className="mt-7 flex flex-wrap gap-2 text-[10px]"><span className="rounded-full bg-white/8 px-3 py-2">PLANNED</span><span className="rounded-full bg-white/8 px-3 py-2">GATE PASSED</span><span className="rounded-full bg-white/8 px-3 py-2">APPROVED TO SPEND</span><span className="rounded-full bg-[#b9ff66] px-3 py-2 text-black">RECEIPT</span></div></div>
      <div className="rounded-[26px] border border-white/10 bg-white/[.055] p-6"><div className="flex items-center gap-2"><ReceiptText className="h-4 w-4 text-[#b9ff66]"/><p className="text-sm font-medium">Render receipt</p></div><div className="mt-6 space-y-4 text-xs"><ReceiptRow label="State" value="render_queued"/><ReceiptRow label="Provider" value="configured media boundary"/><ReceiptRow label="Request" value="request-id retained"/><ReceiptRow label="Script" value="approved source retained"/><ReceiptRow label="Publish" value="human approval required"/></div></div>
    </div></section>

    <section id="agents" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-black/35">Agent-callable</p><h2 className="mt-4 max-w-xl text-4xl font-semibold leading-[1.01] tracking-[-0.06em] sm:text-5xl">Use the studio. Or call the same factory from your agent.</h2><p className="mt-5 max-w-xl text-base leading-7 text-black/48">The UI and MCP surface resolve to the same gated production contract. An agent can build the plan freely; a paid render still requires explicit approval.</p><div className="mt-7 flex flex-wrap gap-2 text-[10px] font-medium"><span className="rounded-full border border-black/8 bg-white px-3 py-2">UI</span><span className="rounded-full border border-black/8 bg-white px-3 py-2">MCP</span><span className="rounded-full border border-black/8 bg-white px-3 py-2">REST</span><span className="rounded-full border border-black/8 bg-white px-3 py-2">CLI</span></div></div><div className="rounded-[26px] border border-black/7 bg-white p-6 shadow-[0_22px_70px_rgba(0,0,0,.07)]"><div className="flex items-center gap-2 text-xs text-black/38"><Bot className="h-4 w-4 text-[#2357ff]"/>Agent request</div><p className="mt-5 text-xl leading-7 tracking-[-0.03em]">Build a UGC batch for this product. Show me the scripts and gate results. Do not spend on generation yet.</p><div className="mt-6 grid gap-2 sm:grid-cols-2"><TrustCard title="Plan" body="No paid media call."/><TrustCard title="Render" body="Requires approved: true."/></div></div></div></section>

    <section className="mx-auto max-w-6xl px-5 pb-24 sm:px-8"><div className="grid gap-6 overflow-hidden rounded-[32px] bg-[#dfff67] px-6 py-12 sm:px-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-black/45">Founding Ad Batch</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.06em] sm:text-5xl">3 ads. 3 angles. $249.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-black/55">A bounded pilot for brands that want to test the factory with real creative before committing to another software subscription.</p></div><Link href="/pricing" className="inline-flex items-center justify-center gap-2 rounded-full bg-black px-6 py-3 text-sm font-medium text-white">See what is included <ArrowRight className="h-4 w-4"/></Link></div></section>

    <footer className="border-t border-black/7 px-5 py-8 text-xs text-black/38 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><span>Social Studio · Founding pilot</span><div className="flex gap-5"><Link href="/pricing">Pilot</Link><Link href="/studio">Studio</Link><Link href="/blog">Notes</Link></div></div></footer>
  </main>;
}

function ProofRow({text,done=false}:{text:string;done?:boolean}){return <div className="flex items-center gap-2 text-xs text-black/50"><span className={`h-2 w-2 rounded-full ${done?"bg-[#159653]":"bg-black/14"}`}/>{text}</div>}
function ReceiptRow({label,value}:{label:string;value:string}){return <div className="grid grid-cols-[85px_1fr] gap-3 border-b border-white/8 pb-4 last:border-0 last:pb-0"><span className="text-white/30">{label}</span><span className="text-white/66">{value}</span></div>}
function TrustCard({title,body}:{title:string;body:string}){return <div className="rounded-xl bg-[#f5f5f2] p-4"><div className="flex items-center gap-2"><Check className="h-3.5 w-3.5 text-[#159653]"/><p className="text-xs font-medium">{title}</p></div><p className="mt-2 text-[11px] leading-5 text-black/42">{body}</p></div>}
