import Link from "next/link";
import { ArrowRight, Bot, Check, FileSearch, Film, ReceiptText, ShieldCheck, Sparkles } from "lucide-react";

const steps = [
  { n:"01", title:"Learn", body:"Pull together the product, customer pain, brand context, and the angles worth testing.", icon:FileSearch },
  { n:"02", title:"Shape", body:"Turn the signal into scripts, concepts, and creative variations your team can actually review.", icon:ShieldCheck },
  { n:"03", title:"Make", body:"Generate UGC-style creative only after the plan and cost are clear.", icon:Film },
  { n:"04", title:"Learn again", body:"Keep approvals, output, and real performance evidence attached to the work so the next round gets smarter.", icon:ReceiptText },
];

export default function LandingPage() {
  return <main className="min-h-screen bg-[#f4f3ef] text-[#151613]">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8">
      <Link href="/" className="text-lg font-semibold tracking-[-0.04em]">Buffer Blaster</Link>
      <nav className="hidden items-center gap-7 text-sm text-black/60 md:flex"><Link href="#system">System</Link><Link href="#control">Control</Link><Link href="#agents">Agents</Link><Link href="/pricing">Access</Link></nav>
      <div className="flex items-center gap-2"><Link href="/studio" className="hidden rounded-full px-4 py-2 text-sm font-medium sm:block">Open Studio</Link><Link href="#access" className="rounded-full bg-black px-4 py-2.5 text-sm font-medium text-white">See how we use it</Link></div>
    </header>

    <section className="mx-auto max-w-7xl px-5 pb-16 pt-14 text-center sm:px-8 sm:pt-24">
      <div className="mx-auto inline-flex items-center gap-2 rounded-full border border-black/10 bg-white px-3.5 py-2 text-[10px] font-semibold uppercase tracking-[0.15em] text-black/60"><Sparkles className="h-3.5 w-3.5 text-[#2357ff]"/>Private creative infrastructure</div>
      <h1 className="mx-auto mt-6 max-w-6xl text-balance text-5xl font-semibold leading-[.92] tracking-[-0.075em] sm:text-7xl lg:text-[94px]">Find the angle.<br/>Make the ad.<br/><span className="text-black/45">Learn what works.</span></h1>
      <p className="mx-auto mt-7 max-w-3xl text-balance text-base leading-7 text-black/62 sm:text-lg">Buffer Blaster is the private creative system we use to turn product truth and customer signals into testable UGC-style ads — with the approvals, cost controls, and learning loop kept in one place.</p>
      <div className="mt-8 flex flex-col justify-center gap-2 sm:flex-row"><Link href="#system" className="inline-flex items-center justify-center gap-2 rounded-full bg-black px-6 py-3 text-sm font-medium text-white">See the system <ArrowRight className="h-4 w-4"/></Link><Link href="/studio" className="inline-flex items-center justify-center rounded-full border border-black/10 bg-white px-6 py-3 text-sm font-medium">Open the Studio</Link></div>
      <div className="mx-auto mt-8 flex max-w-3xl flex-wrap justify-center gap-x-5 gap-y-2 text-[11px] text-black/55"><span className="inline-flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-[#159653]"/>Built for client work</span><span className="inline-flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-[#159653]"/>Human approval before paid actions</span><span className="inline-flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-[#159653]"/>Usable by people or agents</span></div>

      <div className="relative mx-auto mt-16 max-w-6xl overflow-hidden rounded-[26px] border border-black/8 bg-[#deded9] p-3 text-left shadow-[0_35px_110px_rgba(0,0,0,.12)]">
        <div className="rounded-[20px] bg-[#fbfbf9] p-5 sm:p-7">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs text-black/50">Client workspace · Product launch</p><h2 className="mt-1 text-xl font-semibold tracking-tight">Three angles. One clear production trail.</h2></div><span className="self-start rounded-full bg-[#ecf8f1] px-3 py-1.5 text-[10px] font-semibold text-[#117341]">READY TO REVIEW</span></div>
          <div className="mt-6 grid gap-3 md:grid-cols-4">{steps.map(({n,title,body,icon:Icon},index)=><article key={title} className={`border-t pt-4 ${index===2?"border-[#2357ff]":"border-black/15"}`}><div className="flex items-center justify-between"><span className="text-[9px] font-semibold tracking-[.14em] text-black/40">{n}</span><Icon className="h-4 w-4 text-black/45"/></div><p className="mt-5 text-sm font-semibold">{title}</p><p className="mt-2 text-[11px] leading-5 text-black/58">{body}</p></article>)}</div>
          <div className="mt-8 grid gap-3 md:grid-cols-[1.3fr_.7fr]">
            <div className="rounded-2xl bg-[#10110f] p-5 text-white"><div className="flex items-center gap-2 text-xs text-white/55"><Film className="h-4 w-4 text-[#b9ff66]"/>Creative angle · problem and tension</div><p className="mt-4 max-w-xl text-lg leading-7 tracking-[-0.02em]">“I kept paying for coffee that still tasted flat. Better beans did not fix the part I was getting wrong every morning.”</p><div className="mt-5 flex flex-wrap gap-2 text-[9px]"><span className="rounded-full bg-white/10 px-3 py-1.5">24 WORDS</span><span className="rounded-full bg-white/10 px-3 py-1.5">PROBLEM-LED</span><span className="rounded-full bg-[#b9ff66] px-3 py-1.5 text-black">READY FOR REVIEW</span></div></div>
            <div className="border-t border-black/15 pt-5 md:border-l md:border-t-0 md:pl-5 md:pt-0"><div className="flex items-center gap-2"><ReceiptText className="h-4 w-4 text-[#2357ff]"/><p className="text-xs font-medium">What stays attached</p></div><div className="mt-4 space-y-3"><ProofRow text="Research and brand context" done/><ProofRow text="Script and creative decision" done/><ProofRow text="Human approval"/><ProofRow text="Cost and performance evidence"/></div></div>
          </div>
        </div>
      </div>
    </section>

    <section className="border-y border-black/7 bg-[#e8e7e3] py-8"><div className="mx-auto flex max-w-5xl flex-wrap items-center justify-center gap-x-10 gap-y-4 px-5 text-[10px] font-semibold tracking-[0.14em] text-black/48"><span>ECOMMERCE</span><span>SHOPIFY</span><span>CLIENT TEAMS</span><span>AGENCIES</span><span>AI AGENTS</span></div></section>

    <section id="system" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28">
      <div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div className="lg:sticky lg:top-12"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-black/48">The system</p><h2 className="mt-4 max-w-xl text-4xl font-semibold leading-[1.01] tracking-[-0.06em] sm:text-5xl">More creative output without adding another pile of tools.</h2><p className="mt-5 max-w-lg text-base leading-7 text-black/60">Most teams assemble research, prompting, video generation, approvals, publishing, and reporting across separate subscriptions. Buffer Blaster gives our operators and clients one governed place to run the creative loop.</p></div><div className="grid gap-x-6 gap-y-10 sm:grid-cols-2">{steps.map(({title,body,icon:Icon},index)=><article key={title} className="border-t border-black/15 pt-5"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#e9e9e5]"><Icon className="h-4 w-4"/></div><p className="mt-6 text-[10px] uppercase tracking-[.15em] text-black/44">Step {index+1}</p><h3 className="mt-2 text-xl font-semibold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-6 text-black/58">{body}</p></article>)}</div></div>
    </section>

    <section id="control" className="bg-[#10110f] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-28">
      <div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-white/48">Control stays with the operator</p><h2 className="mt-4 max-w-2xl text-4xl font-semibold leading-[1.01] tracking-[-0.06em] sm:text-5xl">Automation should remove busywork, not remove judgment.</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/58">The system can research, draft, generate, organize, and prepare the next move. Paid generation, publishing, and ad activation remain explicit decisions, with limits enforced on the server.</p><div className="mt-7 flex flex-wrap gap-2 text-[10px]"><span className="rounded-full bg-white/8 px-3 py-2">PLAN</span><span className="rounded-full bg-white/8 px-3 py-2">REVIEW</span><span className="rounded-full bg-white/8 px-3 py-2">APPROVE</span><span className="rounded-full bg-[#b9ff66] px-3 py-2 text-black">LEARN</span></div></div>
      <div className="rounded-[22px] border border-white/10 bg-white/[.055] p-6"><div className="flex items-center gap-2"><ReceiptText className="h-4 w-4 text-[#b9ff66]"/><p className="text-sm font-medium">Every job keeps its evidence</p></div><div className="mt-6 space-y-4 text-xs"><ReceiptRow label="Plan" value="what we are testing"/><ReceiptRow label="Approval" value="who cleared the action"/><ReceiptRow label="Cost" value="what the action is allowed to spend"/><ReceiptRow label="Output" value="what was actually produced"/><ReceiptRow label="Result" value="real evidence when it exists"/></div></div>
    </div></section>

    <section id="agents" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-black/48">Agent-native</p><h2 className="mt-4 max-w-xl text-4xl font-semibold leading-[1.01] tracking-[-0.06em] sm:text-5xl">Use the Studio. Or let your agent call the same system.</h2><p className="mt-5 max-w-xl text-base leading-7 text-black/60">The browser is only one doorway. REST, MCP, and CLI surfaces let an approved agent use the same governed workflow from a client operating system without creating a second process.</p><div className="mt-7 flex flex-wrap gap-2 text-[10px] font-medium"><span className="rounded-full border border-black/10 bg-white px-3 py-2">UI</span><span className="rounded-full border border-black/10 bg-white px-3 py-2">MCP</span><span className="rounded-full border border-black/10 bg-white px-3 py-2">REST</span><span className="rounded-full border border-black/10 bg-white px-3 py-2">CLI</span></div></div><div className="rounded-[22px] border border-black/8 bg-white p-6 shadow-[0_22px_70px_rgba(0,0,0,.06)]"><div className="flex items-center gap-2 text-xs text-black/50"><Bot className="h-4 w-4 text-[#2357ff]"/>Agent request</div><p className="mt-5 text-xl leading-7 tracking-[-0.03em]">Build three UGC angles for this product. Keep them on-brand. Show me the plan and estimated cost before anything paid happens.</p><div className="mt-6 grid gap-2 sm:grid-cols-2"><TrustCard title="Prepare" body="Research and creative work can run automatically."/><TrustCard title="Commit" body="Consequential actions still require approval."/></div></div></div></section>

    <section id="access" className="mx-auto max-w-6xl px-5 pb-24 sm:px-8"><div className="overflow-hidden rounded-[28px] bg-[#dfff67] px-6 py-12 sm:px-10"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-black/50">Private client infrastructure</p><div className="mt-4 grid gap-8 lg:grid-cols-[1fr_.9fr] lg:items-end"><div><h2 className="max-w-3xl text-4xl font-semibold tracking-[-0.06em] sm:text-5xl">We sell the outcome. Buffer Blaster is how we deliver it.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-black/62">It is not positioned as another low-cost token subscription. We operate it inside client engagements, or deploy a private instance when a team needs its own creative infrastructure.</p></div><div className="flex flex-col gap-2 sm:flex-row lg:justify-end"><Link href="/pricing" className="inline-flex items-center justify-center gap-2 rounded-full bg-black px-6 py-3 text-sm font-medium text-white">See access options <ArrowRight className="h-4 w-4"/></Link><Link href="/studio" className="inline-flex items-center justify-center rounded-full border border-black/15 px-6 py-3 text-sm font-medium">View Studio</Link></div></div></div></section>

    <footer className="border-t border-black/7 px-5 py-8 text-xs text-black/50 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><span>Buffer Blaster · Private creative infrastructure</span><div className="flex gap-5"><Link href="/pricing">Access</Link><Link href="/studio">Studio</Link><Link href="/blog">Notes</Link></div></div></footer>
  </main>;
}

function ProofRow({text,done=false}:{text:string;done?:boolean}){return <div className="flex items-center gap-2 text-xs text-black/60"><span className={`h-2 w-2 rounded-full ${done?"bg-[#159653]":"bg-black/18"}`}/>{text}</div>}
function ReceiptRow({label,value}:{label:string;value:string}){return <div className="grid grid-cols-[85px_1fr] gap-3 border-b border-white/8 pb-4 last:border-0 last:pb-0"><span className="text-white/42">{label}</span><span className="text-white/72">{value}</span></div>}
function TrustCard({title,body}:{title:string;body:string}){return <div className="rounded-xl bg-[#f5f5f2] p-4"><div className="flex items-center gap-2"><Check className="h-3.5 w-3.5 text-[#159653]"/><p className="text-xs font-medium">{title}</p></div><p className="mt-2 text-[11px] leading-5 text-black/58">{body}</p></div>}
